name: Build CoopAndreas

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Xmake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Setup Plugin-SDK
        shell: bash
        run: |
          git clone --depth 1 https://github.com/DK22Pac/plugin-sdk.git github_plugin_sdk
          mkdir -p github_plugin_sdk/output/lib

      - name: Build
        shell: bash
        run: |
          export PLUGIN_SDK_DIR="$(pwd)/github_plugin_sdk"
          
          # Конфигурируем проект
          # --cxflags: только для C++ (лечит injector.hpp)
          # --cflags: для C (не трогаем enet)
          xmake f -a x86 -m release -y \
            --cxflags="/permissive- /FI type_traits /FI algorithm"
          
          xmake build server
          xmake build proxy
          xmake build client

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CoopAndreas-Binaries
          path: |
            build/windows/x86/release/server.exe
            build/windows/x86/release/proxy.dll
            build/windows/x86/release/CoopAndreasSA.dll
          if-no-files-found: warn
