name: Build on Windows

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Configure and Build
        run: |
          # Конфигурируем проект под x86 (как в вашем xmake.lua)
          # Устанавливаем общую директорию для бинарников в 'dist'
          xmake f -a x86 -m release -o dist
          xmake build server
          xmake build proxy
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CoopAndreas-Build
          # Теперь все скомпилированные файлы (exe, dll) будут лежать здесь
          path: dist/windows/x86/release/*
